### PR TITLE
pass empty array if category is missing

### PR DESCRIPTION
**Pull request by WesleyDRobinson**
previously `categories: [null]` was sent and it was causing 400 error in Iterable:
https://gist.github.com/WesleyDRobinson/aab44d9ea1ce4be37444ec02373bf573#file-iterable-json-L27-L29

error message:
```
"code\":\"BadJsonBody\",\"params\":{\"obj.items[0].categories[0]\":[{\"msg\":\"error.expected.jsstring\",\"args\":[]}]}
```

### CODE REVIEW

**Comment by WesleyDRobinson** [comment]
@hankim813 @tsholmes for review and can I request someone to handle the deployment side?

**Comment by WesleyDRobinson** [comment]
alright! think I've done it; back to you @hankim813 :handshake:

**Comment by hankim813** [comment]
@WesleyDRobinson thanks! will deploy monday

**Comment by hankim813** [comment]
@WesleyDRobinson deployed!

**Pull request merged**
