### PR TITLE
Map 'phone' to 'phoneNumber'

### PR DESCRIPTION
**Pull request by dontgitit**
Map "phone" in Segment to "phoneNumber" for Iterable

### CODE REVIEW

**Comment by dontgitit** [comment]
mind taking a look when you get the chance @f2prateek ?

**Comment by hankim813** [comment]
@dontgitit thanks for the PR. I think you can accomplish this by doing this on line 33:

```
var traits = traverse(identify.traits({ phone: 'phoneNumber' }));
```

.traits() function takes an alias object. I think that keeps it pretty clean.

**Comment by dontgitit** [comment]
thanks for the tip @hankim813 , let me try that out

**Comment by dontgitit** [comment]
works! much nicer, I agree!

**Comment by f2prateek** [comment]
LGTM

**Pull request merged**
